/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdaptationSummaryCard: typeof import('./src/components/AdaptationSummaryCard.vue')['default']
    AntSpecializationCard: typeof import('./src/components/AntSpecializationCard.vue')['default']
    ColonyStatusCard: typeof import('./src/components/ColonyStatusCard.vue')['default']
    EvolutionUpgradeItem: typeof import('./src/components/EvolutionUpgradeItem.vue')['default']
    GeneratorInfoDialog: typeof import('./src/components/GeneratorInfoDialog.vue')['default']
    GeneratorItem: typeof import('./src/components/GeneratorItem.vue')['default']
    GeneratorUpgradeItem: typeof import('./src/components/GeneratorUpgradeItem.vue')['default']
    GeneratorUpgradeModal: typeof import('./src/components/GeneratorUpgradeModal.vue')['default']
    HoldableButton: typeof import('./src/components/HoldableButton.vue')['default']
    NextUnlockableGenerator: typeof import('./src/components/NextUnlockableGenerator.vue')['default']
    OfflineProgressModal: typeof import('./src/components/OfflineProgressModal.vue')['default']
    PWAInstallButton: typeof import('./src/components/PWAInstallButton.vue')['default']
    PWAUpdateNotification: typeof import('./src/components/PWAUpdateNotification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
