/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutEvolutionDialog: typeof import('./src/components/AboutEvolutionDialog.vue')['default']
    AchievementNotification: typeof import('./src/components/AchievementNotification.vue')['default']
    AchievementsModal: typeof import('./src/components/AchievementsModal.vue')['default']
    AdaptationSummaryCard: typeof import('./src/components/AdaptationSummaryCard.vue')['default']
    AntHierarchySection: typeof import('./src/components/AntHierarchySection.vue')['default']
    AntSpecializationCard: typeof import('./src/components/AntSpecializationCard.vue')['default']
    ColonyStatusCard: typeof import('./src/components/ColonyStatusCard.vue')['default']
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    EquipmentSection: typeof import('./src/components/EquipmentSection.vue')['default']
    EvolutionConfirmationDialog: typeof import('./src/components/EvolutionConfirmationDialog.vue')['default']
    EvolutionStatusSection: typeof import('./src/components/EvolutionStatusSection.vue')['default']
    EvolutionUpgradeItem: typeof import('./src/components/EvolutionUpgradeItem.vue')['default']
    GeneratorInfoDialog: typeof import('./src/components/GeneratorInfoDialog.vue')['default']
    GeneratorItem: typeof import('./src/components/GeneratorItem.vue')['default']
    GeneratorUpgradeItem: typeof import('./src/components/GeneratorUpgradeItem.vue')['default']
    GeneratorUpgradeModal: typeof import('./src/components/GeneratorUpgradeModal.vue')['default']
    HoldableButton: typeof import('./src/components/HoldableButton.vue')['default']
    HomeColonyStatusCard: typeof import('./src/components/HomeColonyStatusCard.vue')['default']
    InventorySection: typeof import('./src/components/InventorySection.vue')['default']
    InventoryTabsNavigation: typeof import('./src/components/InventoryTabsNavigation.vue')['default']
    ItemModal: typeof import('./src/components/ItemModal.vue')['default']
    LockedSlotModal: typeof import('./src/components/LockedSlotModal.vue')['default']
    MetamorphosisCard: typeof import('./src/components/MetamorphosisCard.vue')['default']
    MultiplierBreakdownModal: typeof import('./src/components/MultiplierBreakdownModal.vue')['default']
    NextUnlockableGenerator: typeof import('./src/components/NextUnlockableGenerator.vue')['default']
    OfflineProgressModal: typeof import('./src/components/OfflineProgressModal.vue')['default']
    PWAInstallButton: typeof import('./src/components/PWAInstallButton.vue')['default']
    PWAUpdateNotification: typeof import('./src/components/PWAUpdateNotification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTopButton: typeof import('./src/components/ScrollToTopButton.vue')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
    UpgradeFilters: typeof import('./src/components/UpgradeFilters.vue')['default']
    UpgradeGrid: typeof import('./src/components/UpgradeGrid.vue')['default']
    UpgradeTabsNavigation: typeof import('./src/components/UpgradeTabsNavigation.vue')['default']
  }
}
