<script setup lang="ts">
import { computed, ref } from 'vue'
import { useGameStore } from '@/stores/gameStore'
import { useGeneratorStore } from '@/stores/generatorStore'
import { useGeneratorUpgradeStore } from '@/stores/generatorUpgradeStore'
import { formatDecimal } from '@/utils/decimalUtils'
import GeneratorItem from '@/components/GeneratorItem.vue'
import GeneratorUpgradeItem from '@/components/GeneratorUpgradeItem.vue'
import HoldableButton from '@/components/HoldableButton.vue'
import NextUnlockableGenerator from '@/components/NextUnlockableGenerator.vue'
import ColonyStatusCard from '@/components/ColonyStatusCard.vue'
import AdaptationSummaryCard from '@/components/AdaptationSummaryCard.vue'
import AntSpecializationCard from '@/components/AntSpecializationCard.vue'
import GeneratorInfoDialog from '@/components/GeneratorInfoDialog.vue'
import GeneratorUpgradeModal from '@/components/GeneratorUpgradeModal.vue'
import { generatorInfo } from '@/constants/generatorInfo'
import type { GeneratorId } from '@/types/generators'

// Import shared styles
import '@/assets/styles/animations.css'

const gameStore = useGameStore()
const generatorStore = useGeneratorStore()
const generatorUpgradeStore = useGeneratorUpgradeStore()

// Get unlocked generators
const unlockedGenerators = computed(() => generatorStore.unlockedGenerators)

// Get the next unlockable generator
const nextUnlockableGenerator = computed(() => generatorStore.nextUnlockableGenerator)

// Food per second (formatted)
const formattedFoodPerSecond = computed(() => {
  return formatDecimal(generatorStore.foodPerSecond, 2)
})

// Get worker ants
const workerAnts = computed(() => {
  return generatorStore.getGenerator('worker')
})

// Calculate auto-generated worker ants
const autoGeneratedWorkers = computed(() => {
  if (!workerAnts.value) return 0
  return workerAnts.value.count.sub(workerAnts.value.manualPurchases)
})

// Format auto-generated workers for display
const formattedAutoGeneratedWorkers = computed(() => {
  return generatorStore.formatGeneratorCount('worker')
})

// Get unlocked generator IDs for level cards
const unlockedGeneratorIds = computed(() => {
  return unlockedGenerators.value.map(generator => generator.id as GeneratorId)
})

// Selected generator for upgrades
const selectedGenerator = ref<GeneratorId | null>(null)

// Show/hide upgrade modal
const showUpgradeModal = ref(false)

// Open upgrade modal for a specific generator
const openUpgradeModal = (generatorId: GeneratorId) => {
  selectedGenerator.value = generatorId
  showUpgradeModal.value = true
}

// Close upgrade modal
const closeUpgradeModal = () => {
  showUpgradeModal.value = false
}

// Get total points available
const totalPointsAvailable = computed(() => {
  let total = 0
  Object.values(generatorUpgradeStore.generatorPoints).forEach(points => {
    total += points.toNumber()
  })
  return total
})

// Show/hide generator info dialog
const showGeneratorInfo = ref(false)
const toggleGeneratorInfo = () => {
  showGeneratorInfo.value = !showGeneratorInfo.value
}

// Get highest level generator
const highestLevelGenerator = computed(() => {
  let highest = { id: 'worker' as GeneratorId, level: 0 }

  unlockedGeneratorIds.value.forEach(id => {
    const level = generatorUpgradeStore.generatorLevels[id]?.toNumber() || 0
    if (level > highest.level) {
      highest = { id, level }
    }
  })

  return highest
})

// Get level requirement description
const levelRequirementDescription = computed(() => {
  if (!selectedGenerator.value) return ''
  switch (selectedGenerator.value) {
    case 'worker':
      return 'Levels up based on ticks in current evolution'
    case 'nursery':
      return 'Levels up based on amount of food gained'
    case 'queenChamber':
      return 'Levels up based on total manual purchases'
    case 'colony':
      return 'Levels up based on amount of upgrades purchased'
    default:
      return ''
  }
})

// Get level requirement unit
const levelRequirementUnit = computed(() => {
  if (!selectedGenerator.value) return ''
  switch (selectedGenerator.value) {
    case 'worker':
      return 'ticks'
    case 'nursery':
      return 'food'
    case 'queenChamber':
      return 'purchases'
    case 'colony':
      return 'upgrades'
    default:
      return ''
  }
})

// Manual food collection
const collectFood = () => {
  generatorStore.food = generatorStore.food.add(1)
}
</script>

<template>
  <div class="space-y-4">
    <!-- Main Dashboard - Colony Overview -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <!-- Colony Status -->
      <ColonyStatusCard className="md:col-span-2" />

      <!-- Right Column: Adaptation Summary -->
      <AdaptationSummaryCard @show-info="toggleGeneratorInfo" />
    </div>

    <!-- Generator Levels -->
    <section class="bg-gradient-to-br from-amber-100 to-amber-50 rounded-xl p-3 shadow-md">
      <h2 class="text-base font-bold mb-2 flex items-center">
        <span class="i-heroicons-star text-amber-700 mr-2"></span>
        Ant Specialization Levels
      </h2>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        <AntSpecializationCard v-for="generatorId in unlockedGeneratorIds" :key="generatorId"
          :generator-id="generatorId" :name="generatorInfo[generatorId]?.name" :icon="generatorInfo[generatorId]?.icon"
          @upgrade="openUpgradeModal" />
      </div>
    </section>

    <!-- Generator Info Dialog -->
    <GeneratorInfoDialog :show="showGeneratorInfo" @close="toggleGeneratorInfo" />

    <!-- Generator Upgrade Modal -->
    <GeneratorUpgradeModal :show="showUpgradeModal" :selected-generator="selectedGenerator"
      :generator-info="generatorInfo" @close="closeUpgradeModal" />
  </div>
</template>
