<script setup lang="ts">
// Home page for the idle ant farm game
import { computed } from 'vue'
import { useGameStore } from '@/stores/gameStore'
import { useGeneratorStore } from '@/stores/generatorStore'
import { usePrestigeStore } from '@/stores/prestigeStore'
import { formatDecimal } from '@/utils/decimalUtils'
import GeneratorItem from '@/components/GeneratorItem.vue'

const gameStore = useGameStore()
const generatorStore = useGeneratorStore()
const prestigeStore = usePrestigeStore()

// Get unlocked generators
const unlockedGenerators = computed(() => generatorStore.unlockedGenerators)

// Food per second (formatted)
const formattedFoodPerSecond = computed(() => {
  return formatDecimal(generatorStore.foodPerSecond, 2)
})

// Manual food collection
const collectFood = () => {
  generatorStore.food = generatorStore.food.add(1)
}

// Get worker ants
const workerAnts = computed(() => {
  return generatorStore.getGenerator('worker')
})

// Calculate auto-generated worker ants
const autoGeneratedWorkers = computed(() => {
  if (!workerAnts.value) return 0
  return workerAnts.value.count.sub(workerAnts.value.manualPurchases)
})

// Format auto-generated workers for display
const formattedAutoGeneratedWorkers = computed(() => {
  return generatorStore.formatGeneratorCount('worker')
})

// Loop progress percentage
const loopProgressPercentage = computed(() => {
  return Math.round(prestigeStore.currentLoopProgress * 100)
})
</script>

<template>
  <div class="space-y-6">
    <!-- Colony Status -->
    <section class="bg-gradient-to-br from-amber-100 to-amber-50 rounded-xl p-5 shadow-md">
      <h2 class="text-lg font-bold mb-3 flex items-center">
        <span class="i-heroicons-chart-bar text-amber-700 mr-2"></span>
        Colony Status
      </h2>

      <div class="grid grid-cols-2 gap-4">
        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-amber-200">
          <div class="text-xs text-amber-700 font-medium">Food</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-cake text-amber-600 mr-2 text-sm"></span>
            {{ generatorStore.formatFood() }}
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-amber-200">
          <div class="text-xs text-amber-700 font-medium">Food per Tick</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-arrow-trending-up text-amber-600 mr-2 text-sm"></span>
            {{ formattedFoodPerSecond }}
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-amber-200">
          <div class="text-xs text-amber-700 font-medium">Worker Ants</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-bug-ant text-amber-600 mr-2 text-sm"></span>
            {{ generatorStore.formatGeneratorCount('worker') }}
          </div>
          <div class="text-xs text-amber-600 mt-1" v-if="autoGeneratedWorkers.gt(0)">
            ({{ formattedAutoGeneratedWorkers }} auto-generated)
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-amber-200">
          <div class="text-xs text-amber-700 font-medium">Loop Progress</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-arrow-path-rounded-square text-amber-600 mr-2 text-sm"></span>
            {{ loopProgressPercentage }}%
          </div>

          <!-- Loop progress bar -->
          <div class="h-1.5 bg-amber-100 rounded-full mt-2 overflow-hidden">
            <div class="h-full bg-amber-500 transition-all duration-300 ease-out"
              :style="{ width: `${loopProgressPercentage}%` }"></div>
          </div>
          <div class="text-xs text-amber-600 mt-1">
            {{ Math.round(prestigeStore.currentLoopProgress * prestigeStore.ticksPerLoop.toNumber() * 10) / 10 }} / {{
              formatDecimal(prestigeStore.ticksPerLoop, 1) }} ticks
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-amber-200">
          <div class="text-xs text-amber-700 font-medium">Food for Next Loop</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-cake text-amber-600 mr-2 text-sm"></span>
            {{ generatorStore.formatFood() }} / {{ formatDecimal(prestigeStore.foodForNextLoop, 0) }}
          </div>
          <div class="text-xs text-amber-600 mt-1">
            Need {{ formatDecimal(prestigeStore.foodForNextLoop, 0) }} food to complete a loop
          </div>

          <!-- Food progress bar -->
          <div class="h-1.5 bg-amber-100 rounded-full mt-2 overflow-hidden">
            <div class="h-full bg-amber-500 transition-all duration-300 ease-out"
              :style="{ width: `${Math.min(100, (generatorStore.food.div(prestigeStore.foodForNextLoop).toNumber()) * 100)}%` }">
            </div>
          </div>
        </div>
      </div>

      <div class="mt-4 bg-amber-50 p-3 rounded-lg border border-amber-200">
        <p class="text-xs text-amber-800 flex items-start">
          <span class="i-heroicons-information-circle text-amber-600 mr-1.5 mt-0.5"></span>
          <span>Prices are based only on manual purchases. Auto-generated units don't increase costs!</span>
        </p>
      </div>
    </section>



    <!-- Generators -->
    <section class="bg-gradient-to-br from-amber-100 to-amber-50 rounded-xl p-5 shadow-md">
      <h2 class="text-lg font-bold mb-3 flex items-center">
        <span class="i-heroicons-building-storefront text-amber-700 mr-2"></span>
        Expand Your Colony
      </h2>

      <div class="space-y-4">
        <GeneratorItem v-for="generator in unlockedGenerators" :key="generator.id" :generator="generator" />
      </div>
    </section>

    <!-- Evolution Status -->
    <section class="bg-gradient-to-br from-purple-100 to-purple-50 rounded-xl p-5 shadow-md">
      <h2 class="text-lg font-bold mb-3 flex items-center">
        <span class="i-heroicons-sparkles text-purple-700 mr-2"></span>
        Evolution Progress
      </h2>

      <div class="grid grid-cols-2 gap-4">
        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-purple-200">
          <div class="text-xs text-purple-700 font-medium">Evolution Count</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-sparkles text-purple-600 mr-2 text-sm"></span>
            {{ prestigeStore.formatEvolutionCount() }}
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-purple-200">
          <div class="text-xs text-purple-700 font-medium">Evolution Points</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-sparkles text-purple-600 mr-2 text-sm"></span>
            {{ prestigeStore.formatEP() }}
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-purple-200">
          <div class="text-xs text-purple-700 font-medium">Loops Completed</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-arrow-path-rounded-square text-purple-600 mr-2 text-sm"></span>
            {{ prestigeStore.formatLoopsCompleted() }} / {{ formatDecimal(prestigeStore.requiredLoops, 1) }}
          </div>

          <!-- Loops completed progress bar -->
          <div class="h-1.5 bg-purple-100 rounded-full mt-2 overflow-hidden">
            <div class="h-full bg-purple-500 transition-all duration-300 ease-out"
              :style="{ width: `${Math.min(100, (prestigeStore.loopsCompleted.div(prestigeStore.requiredLoops).toNumber() * 100))}%` }">
            </div>
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-purple-200">
          <div class="text-xs text-purple-700 font-medium">Loop Requirements</div>
          <div class="text-sm font-medium flex items-center mt-1">
            <span class="i-heroicons-clock text-purple-600 mr-1.5 text-xs"></span>
            {{ formatDecimal(prestigeStore.ticksPerLoop, 1) }} ticks
          </div>
          <div class="text-sm font-medium flex items-center mt-1">
            <span class="i-heroicons-cake text-purple-600 mr-1.5 text-xs"></span>
            {{ formatDecimal(prestigeStore.foodForNextLoop, 0) }} food
          </div>
        </div>
      </div>

      <div class="mt-3 text-center">
        <router-link to="/upgrades"
          class="inline-block px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-md text-sm font-medium">
          View Evolution Upgrades
        </router-link>
      </div>
    </section>
  </div>
</template>
