<script setup lang="ts">
// Home page for the idle ant farm game
import { computed } from 'vue'
import { useGameStore } from '@/stores/gameStore'
import { useGeneratorStore } from '@/stores/generatorStore'
import GeneratorItem from '@/components/GeneratorItem.vue'

const gameStore = useGameStore()
const generatorStore = useGeneratorStore()

// Get unlocked generators
const unlockedGenerators = computed(() => generatorStore.unlockedGenerators)

// Food per second
const foodPerSecond = computed(() => generatorStore.foodPerSecond)

// Manual food collection
const collectFood = () => {
  generatorStore.food = generatorStore.food.add(1)
}

// Get worker ants
const workerAnts = computed(() => {
  return generatorStore.getGenerator('worker')
})

// Calculate auto-generated worker ants
const autoGeneratedWorkers = computed(() => {
  if (!workerAnts.value) return 0
  return workerAnts.value.count.sub(workerAnts.value.manualPurchases)
})

// Format auto-generated workers for display
const formattedAutoGeneratedWorkers = computed(() => {
  return generatorStore.formatGeneratorCount('worker')
})
</script>

<template>
  <div class="space-y-6">
    <!-- Welcome Section -->
    <section class="bg-gradient-to-br from-amber-100 to-amber-50 rounded-xl p-5 shadow-md">
      <h2 class="text-lg font-bold mb-2">Welcome to your Ant Colony!</h2>
      <p class="text-sm text-amber-800">Tap to collect food and grow your colony of industrious ants.</p>

      <div class="mt-6 flex justify-center">
        <button @click="collectFood"
          class="bg-gradient-to-br from-amber-600 to-amber-500 hover:from-amber-700 hover:to-amber-600 text-white font-bold py-4 px-6 rounded-full shadow-lg transform transition-all active:scale-95 active:shadow-md flex items-center">
          <span class="i-heroicons-hand-raised text-2xl mr-2"></span>
          Tap to Collect
        </button>
      </div>
    </section>

    <!-- Colony Status -->
    <section class="bg-gradient-to-br from-amber-100 to-amber-50 rounded-xl p-5 shadow-md">
      <h2 class="text-lg font-bold mb-3 flex items-center">
        <span class="i-heroicons-chart-bar text-amber-700 mr-2"></span>
        Colony Status
      </h2>

      <div class="grid grid-cols-2 gap-4">
        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-amber-200">
          <div class="text-xs text-amber-700 font-medium">Food</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-cake text-amber-600 mr-2 text-sm"></span>
            {{ generatorStore.formatFood() }}
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-amber-200">
          <div class="text-xs text-amber-700 font-medium">Food per Tick</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-arrow-trending-up text-amber-600 mr-2 text-sm"></span>
            {{ foodPerSecond }}
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-amber-200">
          <div class="text-xs text-amber-700 font-medium">Worker Ants</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-bug-ant text-amber-600 mr-2 text-sm"></span>
            {{ generatorStore.formatGeneratorCount('worker') }}
          </div>
          <div class="text-xs text-amber-600 mt-1" v-if="autoGeneratedWorkers.gt(0)">
            ({{ formattedAutoGeneratedWorkers }} auto-generated)
          </div>
        </div>

        <div class="bg-white/80 p-3 rounded-lg shadow-sm border border-amber-200">
          <div class="text-xs text-amber-700 font-medium">Total Ticks</div>
          <div class="text-lg font-bold flex items-center">
            <span class="i-heroicons-clock text-amber-600 mr-2 text-sm"></span>
            {{ gameStore.formattedTotalTicks }}
          </div>
        </div>
      </div>

      <div class="mt-4 bg-amber-50 p-3 rounded-lg border border-amber-200">
        <p class="text-xs text-amber-800 flex items-start">
          <span class="i-heroicons-information-circle text-amber-600 mr-1.5 mt-0.5"></span>
          <span>Prices are based only on manual purchases. Auto-generated units don't increase costs!</span>
        </p>
      </div>
    </section>

    <!-- Generators -->
    <section class="bg-gradient-to-br from-amber-100 to-amber-50 rounded-xl p-5 shadow-md">
      <h2 class="text-lg font-bold mb-3 flex items-center">
        <span class="i-heroicons-building-storefront text-amber-700 mr-2"></span>
        Expand Your Colony
      </h2>

      <div class="space-y-4">
        <GeneratorItem v-for="generator in unlockedGenerators" :key="generator.id" :generator="generator" />
      </div>
    </section>
  </div>
</template>
