<script setup lang="ts">
// Home page for the idle ant farm game
import { computed } from 'vue'
import { useGameStore } from '@/stores/gameStore'
import { useGeneratorStore } from '@/stores/generatorStore'
import { usePrestigeStore } from '@/stores/prestigeStore'
import { formatDecimal } from '@/utils/decimalUtils'
import GeneratorItem from '@/components/GeneratorItem.vue'

const gameStore = useGameStore()
const generatorStore = useGeneratorStore()
const prestigeStore = usePrestigeStore()

// Get unlocked generators
const unlockedGenerators = computed(() => generatorStore.unlockedGenerators)

// Food per second (formatted)
const formattedFoodPerSecond = computed(() => {
  return formatDecimal(generatorStore.foodPerSecond, 2)
})

// Manual food collection
const collectFood = () => {
  generatorStore.food = generatorStore.food.add(1)
}

// Get worker ants
const workerAnts = computed(() => {
  return generatorStore.getGenerator('worker')
})

// Calculate auto-generated worker ants
const autoGeneratedWorkers = computed(() => {
  if (!workerAnts.value) return 0
  return workerAnts.value.count.sub(workerAnts.value.manualPurchases)
})

// Format auto-generated workers for display
const formattedAutoGeneratedWorkers = computed(() => {
  return generatorStore.formatGeneratorCount('worker')
})

// Loop progress percentage
const loopProgressPercentage = computed(() => {
  return Math.round(prestigeStore.currentLoopProgress * 100)
})
</script>

<template>
  <div class="space-y-4">
    <!-- Main Dashboard - Combined Colony Status and Evolution Status -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <!-- Left Column: Colony Status -->
      <section class="bg-gradient-to-br from-amber-100 to-amber-50 rounded-xl p-3 shadow-md md:col-span-2">
        <h2 class="text-base font-bold mb-2 flex items-center">
          <span class="i-heroicons-chart-bar text-amber-700 mr-2"></span>
          Colony Status
        </h2>

        <div class="grid grid-cols-3 gap-2">
          <div class="bg-white/80 p-2 rounded-lg shadow-sm border border-amber-200">
            <div class="text-xs text-amber-700 font-medium">Food</div>
            <div class="text-sm font-bold flex items-center">
              <span class="i-heroicons-cake text-amber-600 mr-1 text-xs"></span>
              {{ generatorStore.formatFood() }}
            </div>
          </div>

          <div class="bg-white/80 p-2 rounded-lg shadow-sm border border-amber-200">
            <div class="text-xs text-amber-700 font-medium">Food/Trip</div>
            <div class="text-sm font-bold flex items-center">
              <span class="i-heroicons-arrow-trending-up text-amber-600 mr-1 text-xs"></span>
              {{ formattedFoodPerSecond }}
            </div>
          </div>

          <div class="bg-white/80 p-2 rounded-lg shadow-sm border border-amber-200">
            <div class="text-xs text-amber-700 font-medium">Worker Ants</div>
            <div class="text-sm font-bold flex items-center">
              <span class="i-heroicons-bug-ant text-amber-600 mr-1 text-xs"></span>
              {{ generatorStore.formatGeneratorCount('worker') }}
            </div>
            <div class="text-xs text-amber-600" v-if="autoGeneratedWorkers.gt(0)">
              ({{ formattedAutoGeneratedWorkers }} auto)
            </div>
          </div>
        </div>

        <!-- Progress Bars Row -->
        <div class="grid grid-cols-2 gap-2 mt-2">
          <div class="bg-white/80 p-2 rounded-lg shadow-sm border border-amber-200">
            <div class="text-xs text-amber-700 font-medium flex justify-between">
              <span>Foraging Cycle</span>
              <span>{{ loopProgressPercentage }}%</span>
            </div>
            <div class="h-1.5 bg-amber-100 rounded-full mt-1 overflow-hidden">
              <div class="h-full bg-amber-500 transition-all duration-300 ease-out"
                :style="{ width: `${loopProgressPercentage}%` }"></div>
            </div>
            <div class="text-xs text-amber-600 mt-1">
              {{ Math.round(prestigeStore.currentLoopProgress * prestigeStore.ticksPerLoop.toNumber() * 10) / 10 }} / {{
                formatDecimal(prestigeStore.ticksPerLoop, 1) }} trips
            </div>
          </div>

          <div class="bg-white/80 p-2 rounded-lg shadow-sm border border-amber-200">
            <div class="text-xs text-amber-700 font-medium flex justify-between">
              <span>Food for Next Cycle</span>
              <span>{{ Math.min(100, Math.round((generatorStore.food.div(prestigeStore.foodForNextLoop).toNumber()) *
                100)) }}%</span>
            </div>
            <div class="h-1.5 bg-amber-100 rounded-full mt-1 overflow-hidden">
              <div class="h-full bg-amber-500 transition-all duration-300 ease-out"
                :style="{ width: `${Math.min(100, (generatorStore.food.div(prestigeStore.foodForNextLoop).toNumber()) * 100)}%` }">
              </div>
            </div>
            <div class="text-xs text-amber-600 mt-1">
              {{ generatorStore.formatFood() }} / {{ formatDecimal(prestigeStore.foodForNextLoop, 0) }} food
            </div>
          </div>
        </div>

        <!-- Info and Button Row -->
        <div class="flex gap-2 mt-2">
          <div class="bg-amber-50 p-2 rounded-lg border border-amber-200 flex-grow text-xs text-amber-800">
            <span class="i-heroicons-information-circle text-amber-600 mr-1 inline-block"></span>
            Prices are based only on manual purchases. Auto-generated units don't increase costs!
          </div>

          <button @click="collectFood"
            class="px-3 py-2 bg-amber-600 hover:bg-amber-700 rounded-lg text-white font-medium transition-colors duration-200 flex items-center justify-center whitespace-nowrap">
            <span class="i-heroicons-hand-raised text-base mr-1"></span>
            Collect Food
          </button>
        </div>
      </section>

      <!-- Right Column: Evolution Status -->
      <section class="bg-gradient-to-br from-purple-100 to-purple-50 rounded-xl p-3 shadow-md">
        <h2 class="text-base font-bold mb-2 flex items-center">
          <span class="i-heroicons-sparkles text-purple-700 mr-2"></span>
          Metamorphosis
        </h2>

        <div class="space-y-2">
          <div class="grid grid-cols-2 gap-2">
            <div class="bg-white/80 p-2 rounded-lg shadow-sm border border-purple-200">
              <div class="text-xs text-purple-700 font-medium">Metamorphosis Count</div>
              <div class="text-sm font-bold flex items-center">
                <span class="i-heroicons-sparkles text-purple-600 mr-1 text-xs"></span>
                {{ prestigeStore.formatEvolutionCount() }}
              </div>
            </div>

            <div class="bg-white/80 p-2 rounded-lg shadow-sm border border-purple-200">
              <div class="text-xs text-purple-700 font-medium">Evolution Points</div>
              <div class="text-sm font-bold flex items-center">
                <span class="i-heroicons-sparkles text-purple-600 mr-1 text-xs"></span>
                {{ prestigeStore.formatEP() }}
              </div>
            </div>
          </div>

          <div class="bg-white/80 p-2 rounded-lg shadow-sm border border-purple-200">
            <div class="text-xs text-purple-700 font-medium flex justify-between">
              <span>Foraging Cycles Completed</span>
              <span>{{ Math.min(100,
                Math.round((prestigeStore.loopsCompleted.div(prestigeStore.requiredLoops).toNumber() * 100))) }}%</span>
            </div>
            <div class="h-1.5 bg-purple-100 rounded-full mt-1 overflow-hidden">
              <div class="h-full bg-purple-500 transition-all duration-300 ease-out"
                :style="{ width: `${Math.min(100, (prestigeStore.loopsCompleted.div(prestigeStore.requiredLoops).toNumber() * 100))}%` }">
              </div>
            </div>
            <div class="text-xs text-purple-600 mt-1">
              {{ prestigeStore.formatLoopsCompleted() }} / {{ formatDecimal(prestigeStore.requiredLoops, 1) }} cycles
            </div>
          </div>

          <div class="bg-white/80 p-2 rounded-lg shadow-sm border border-purple-200">
            <div class="text-xs text-purple-700 font-medium">Cycle Requirements</div>
            <div class="grid grid-cols-2 gap-1 mt-1">
              <div class="text-xs font-medium flex items-center">
                <span class="i-heroicons-clock text-purple-600 mr-1 text-xs"></span>
                {{ formatDecimal(prestigeStore.ticksPerLoop, 1) }} trips
              </div>
              <div class="text-xs font-medium flex items-center">
                <span class="i-heroicons-cake text-purple-600 mr-1 text-xs"></span>
                {{ formatDecimal(prestigeStore.foodForNextLoop, 0) }} food
              </div>
            </div>
          </div>

          <router-link to="/upgrades"
            class="block w-full px-3 py-1.5 bg-purple-600 hover:bg-purple-700 text-white rounded-md text-xs font-medium text-center">
            View Evolutionary Adaptations
          </router-link>
        </div>
      </section>
    </div>

    <!-- Generators -->
    <section class="bg-gradient-to-br from-amber-100 to-amber-50 rounded-xl p-3 shadow-md">
      <h2 class="text-base font-bold mb-2 flex items-center">
        <span class="i-heroicons-cog-6-tooth text-amber-700 mr-2"></span>
        Ant Hierarchy
      </h2>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        <GeneratorItem v-for="generator in unlockedGenerators" :key="generator.id" :generator="generator" />
      </div>
    </section>
  </div>
</template>
