<script setup lang="ts">
import { computed } from 'vue'
import { useGeneratorStore } from '@/stores/generatorStore'
import { usePrestigeStore } from '@/stores/prestigeStore'
import type { Generator } from '@/stores/generatorStore'
import { formatDecimal } from '@/utils/decimalUtils'
import HoldableButton from '@/components/HoldableButton.vue'

const props = defineProps<{
  generator: Generator
}>()

const generatorStore = useGeneratorStore()
const prestigeStore = usePrestigeStore()

// Computed properties
const cost = computed(() => {
  return generatorStore.getGeneratorCost(props.generator.id)
})

const formattedCost = computed(() => {
  return formatDecimal(cost.value, 0)
})

const canAfford = computed(() => {
  return generatorStore.food.gte(cost.value)
})

const formattedCount = computed(() => {
  return formatDecimal(props.generator.count, 0)
})

const formattedManualPurchases = computed(() => {
  return formatDecimal(props.generator.manualPurchases, 0)
})

const autoGenerated = computed(() => {
  return props.generator.count.sub(props.generator.manualPurchases)
})

const formattedAutoGenerated = computed(() => {
  return formatDecimal(autoGenerated.value, 0)
})

const formattedProduction = computed(() => {
  return formatDecimal(props.generator.baseProduction, 1)
})

// Get the production multiplier
const productionMultiplier = computed(() => {
  return generatorStore.getProductionMultiplier(props.generator.id)
})

// Format the production multiplier
const formattedProductionMultiplier = computed(() => {
  return generatorStore.formatProductionMultiplier(props.generator.id)
})

// Calculate actual production with multipliers
const actualProduction = computed(() => {
  return props.generator.baseProduction.mul(productionMultiplier.value)
})

// Format actual production
const formattedActualProduction = computed(() => {
  return formatDecimal(actualProduction.value, 1)
})

// Check if auto-purchase is available for this generator
const autoUpgradeMap = {
  worker: 'autoWorker',
  nursery: 'autoNursery',
  queenChamber: 'autoQueenChamber',
  colony: 'autoColony',
  megacolony: 'autoMegacolony',
  hivemind: 'autoHivemind',
  antopolis: 'autoAntopolis'
}

const hasAutoPurchase = computed(() => {
  const upgradeId = autoUpgradeMap[props.generator.id as keyof typeof autoUpgradeMap]
  if (!upgradeId) return false

  // Check if the upgrade exists and has a level greater than 0
  return prestigeStore.getUpgradeMultiplier(upgradeId).gt(0)
})

// Toggle auto-purchase for this generator
const toggleAutoPurchase = () => {
  generatorStore.toggleAutoPurchase(props.generator.id)
}

// Methods
const buyGenerator = () => {
  if (canAfford.value && !hasMissingDependency.value) {
    generatorStore.buyGenerator(props.generator.id)
  }
}

// Check if this generator has dependencies that aren't met
const hasMissingDependency = computed(() => {
  if (props.generator.id === 'hivemind') {
    const megacolony = generatorStore.getGenerator('megacolony')
    return !megacolony || megacolony.count.eq(0)
  } else if (props.generator.id === 'antopolis') {
    const hivemind = generatorStore.getGenerator('hivemind')
    return !hivemind || hivemind.count.eq(0)
  }
  return false
})

// Get dependency message if applicable
const dependencyMessage = computed(() => {
  if (props.generator.id === 'hivemind') {
    return 'Requires at least one Mega Colony'
  } else if (props.generator.id === 'antopolis') {
    return 'Requires at least one Hive Mind'
  }
  return ''
})

// Get production type based on tier
const productionType = computed(() => {
  switch (props.generator.tier) {
    case 1: return 'food'
    case 2: return 'worker ants'
    case 3: return 'nurseries'
    case 4: return 'queen chambers'
    case 5: return 'colonies'
    case 6: return 'mega colonies'
    case 7: return 'hive minds'
    default: return 'resources'
  }
})
</script>

<template>
  <div class="bg-white rounded-lg shadow-sm overflow-hidden border border-amber-200 transition-all duration-200"
    :class="{ 'opacity-75': !canAfford }">
    <div class="flex flex-col h-full">
      <!-- Header -->
      <div
        class="bg-gradient-to-r from-amber-600 to-amber-500 py-1.5 px-2.5 flex items-center justify-between text-white">
        <div class="flex items-center">
          <span :class="[generator.icon, 'text-lg mr-1.5 text-amber-200']"></span>
          <h3 class="font-bold text-xs md:text-sm">{{ generator.name }}</h3>
        </div>
        <div class="text-xs font-medium bg-amber-700/30 px-1.5 py-0.5 rounded">
          {{ formattedCount }}
        </div>
      </div>

      <!-- Content - more compact with less padding -->
      <div class="px-2.5 pt-2 pb-1 text-amber-900 flex-grow text-xs">
        <!-- Description - shorter margin -->
        <p class="mb-1.5">{{ generator.description }}</p>

        <!-- Stats in a more compact grid -->
        <div class="grid grid-cols-2 gap-x-2 gap-y-0.5 mb-1.5">
          <div class="font-medium text-amber-700">Production:</div>
          <div class="text-right text-amber-700">{{ formattedActualProduction }} {{ productionType }}/trip</div>

          <div class="font-medium text-amber-600">Base × Multiplier:</div>
          <div class="text-right text-amber-600">{{ formattedProduction }} × {{ formattedProductionMultiplier }}</div>

          <div class="font-medium text-amber-700">Bought:</div>
          <div class="text-right text-amber-700">{{ formattedManualPurchases }}</div>

          <div class="font-medium text-amber-700">Generated:</div>
          <div class="text-right text-amber-700">{{ formattedAutoGenerated }}</div>
        </div>

        <!-- Auto-purchase toggle - more compact -->
        <div v-if="hasAutoPurchase" class="flex justify-between items-center mb-1.5 border-t border-amber-100 pt-1.5">
          <span class="font-medium text-amber-800">Auto-purchase:</span>
          <button @click="toggleAutoPurchase"
            class="w-8 h-4 rounded-full relative cursor-pointer transition-colors duration-200 ease-in-out"
            :class="generator.autoPurchaseEnabled ? 'bg-green-500' : 'bg-gray-300'">
            <span
              class="absolute top-0.5 left-0.5 w-3 h-3 bg-white rounded-full shadow transform transition-transform duration-200 ease-in-out"
              :class="generator.autoPurchaseEnabled ? 'translate-x-4' : 'translate-x-0'"></span>
          </button>
        </div>
      </div>

      <!-- Buy button section - more compact -->
      <div class="px-2.5 py-2 mt-auto border-t border-amber-100">
        <!-- Dependency warning message -->
        <div v-if="hasMissingDependency" class="text-xs text-red-600 mb-1 flex items-center">
          <span class="i-heroicons-exclamation-triangle text-xs mr-1"></span>
          {{ dependencyMessage }}
        </div>

        <HoldableButton @action="buyGenerator" :disabled="!canAfford || hasMissingDependency" :class="canAfford && !hasMissingDependency
          ? 'w-full py-1.5 px-2.5 rounded text-xs font-medium bg-amber-600 hover:bg-amber-700 text-white'
          : 'w-full py-1.5 px-2.5 rounded text-xs font-medium bg-gray-200 text-gray-500 cursor-not-allowed'"
          :initial-delay="400" :repeat-interval="150" :accelerate="true" :min-interval="30">
          <span class="i-heroicons-shopping-cart text-xs mr-1"></span>
          Buy for {{ formattedCost }} food
        </HoldableButton>
      </div>
    </div>
  </div>
</template>
